"""ProofBid evidence-driven tender preparation core."""

from .contracts import (
    AnalysisBundle,
    BOMLine,
    BidderFact,
    BidderProfile,
    CatalogItem,
    ComplianceMatch,
    Deviation,
    DocumentType,
    EvidenceRef,
    ExtractionResult,
    MatchStatus,
    MissingItem,
    Requirement,
    RequirementCategory,
    Severity,
    SourceDocument,
    to_primitive,
)
from .extraction import extract_requirements
from .intake import (
    IntakeError,
    OversizedDocumentError,
    PathBoundaryError,
    UnsupportedDocumentError,
    scan_workspace,
)
from .matching import build_analysis, load_bidder_profile, load_catalog
from .planning import (
    ExecutionPlan,
    PlanStep,
    PlanTool,
    PlanValidationError,
    PlanningResult,
    ProviderReceipt,
    TaskInputRef,
    TaskSpec,
    build_task_spec,
    validate_execution_plan,
)


__all__ = [
    "AnalysisBundle",
    "BOMLine",
    "BidderFact",
    "BidderProfile",
    "CatalogItem",
    "ComplianceMatch",
    "Deviation",
    "DocumentType",
    "EvidenceRef",
    "ExecutionPlan",
    "ExtractionResult",
    "IntakeError",
    "MatchStatus",
    "MissingItem",
    "OversizedDocumentError",
    "PlanStep",
    "PlanTool",
    "PlanValidationError",
    "PlanningResult",
    "ProviderReceipt",
    "PathBoundaryError",
    "Requirement",
    "RequirementCategory",
    "Severity",
    "SourceDocument",
    "TaskInputRef",
    "TaskSpec",
    "UnsupportedDocumentError",
    "build_analysis",
    "build_task_spec",
    "extract_requirements",
    "load_bidder_profile",
    "load_catalog",
    "scan_workspace",
    "to_primitive",
    "validate_execution_plan",
]
